export const mainCategories = [
  { label: "Animals / Pets", value: "animals-pets" },
  { label: "Art", value: "art" },
  { label: "Auto", value: "auto" },
  { label: "Blogging", value: "blogging" },
  { label: "Business / Entrepreneur", value: "business-entrepreneur" },
  { label: "Construction", value: "construction" },
  { label: "Directory", value: "directory" },
  { label: "Fashion", value: "fashion" },
  { label: "Education", value: "education" },
  { label: "Energy & Solar Energy", value: "energy-solar-energy" },
  { label: "Entertainment & Music", value: "entertainment-music" },
  { label: "Events", value: "events" },
  { label: "Family / Parenting", value: "family-parenting" },
  { label: "Finance", value: "finance" },
  { label: "Food", value: "food" },
  { label: "Gambling", value: "gambling" },
  { label: "Gaming", value: "gaming" },
  { label: "General", value: "general" },
  { label: "Health & Fitness", value: "health-fitness" },
  { label: "Home & Garden", value: "home-garden" },
  { label: "Industrial", value: "industrial" },
  { label: "Legal", value: "legal" },
  { label: "Lifestyle", value: "lifestyle" },
  { label: "Marijuana / Vaporizers", value: "marijuana-vaporizers" },
  { label: "Marketing", value: "marketing" },
  { label: "Medical", value: "medical" },
  { label: "News", value: "news" },
  { label: "Other", value: "other" },
  { label: "Outdoors", value: "outdoors" },
  { label: "Photography", value: "photography" },
  { label: "Politics", value: "politics" },
  { label: "Real Estate", value: "real-estate" },
  { label: "Religious", value: "religious" },
  { label: "SEO", value: "seo" },
  { label: "Sex & Adult", value: "sex-adult" },
  { label: "Shopping", value: "shopping" },
  { label: "Sports", value: "sports" },
  { label: "Technology", value: "technology" },
  { label: "Travel", value: "travel" },
  { label: "Vehicles", value: "vehicles" },
];