export const tableData = [
    {
      acceptPreconditions: true,
      articleDescription: "",
      country: "en-US",
      description:
        'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
      doFollow: "yes",
      homepageLinkDescription:
        'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
      homepageLinkPrice: 54,
      id: "00f8b896-b2f4-4fa7-adc8-6df1c94eb39b",
      isArticleIncluded: "yes",
      isOwner: false,
      language: "en-GB",
      linksAllowed: "brand-links",
      mainCategories: ["art", "energy-solar-energy", "gaming"],
      normalOfferGuestPosting: 54,
      normalOfferLinkInsertion: 54,
      numberOfLinks: "not-tag",
      numberOfLinksMax: "",
      numberOfLinksMin: "",
      numberOfWords: "not-limited",
      numberOfWordsMaxWords: "",
      numberOfWordsMinWords: "",
      otherLinks: "yes",
      taggingArticles: "not-tag",
      websiteUrl: "https://beyondlabs.io",
    },
    {
      acceptPreconditions: true,
      articleDescription:
        "This is a sample article description for the second item.",
      country: "en-GB",
      description:
        "Another piece of text for demonstration purposes. This could be a summary of an article or a product description.",
      doFollow: "no",
      homepageLinkDescription:
        "Short and sweet description for the homepage link.",
      homepageLinkPrice: 75,
      id: "1a2b3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6",
      isArticleIncluded: "no",
      isOwner: true,
      language: "en-US",
      linksAllowed: "content-links",
      mainCategories: ["politics", "lifestyle"],
      normalOfferGuestPosting: 75,
      normalOfferLinkInsertion: 60,
      numberOfLinks: "limited",
      numberOfLinksMax: "3",
      numberOfLinksMin: "1",
      numberOfWords: "limited",
      numberOfWordsMaxWords: "1000",
      numberOfWordsMinWords: "500",
      otherLinks: "no",
      taggingArticles: "tag",
      websiteUrl: "https://example.com",
    },
    {
      acceptPreconditions: false,
      articleDescription: "Third sample data entry.",
      country: "en-GB",
      description:
        "Ceci est un exemple de description en français pour illustrer la diversité des données.",
      doFollow: "yes",
      homepageLinkDescription:
        "Description du lien de la page d'accueil en français.",
      homepageLinkPrice: 40,
      id: "9z8y7x6w-5v4u-3t2s-1r0q-p9o8n7m6l5k4",
      isArticleIncluded: "yes",
      isOwner: false,
      language: "hi",
      linksAllowed: "mixed",
      mainCategories: ["food", "education"],
      normalOfferGuestPosting: 40,
      normalOfferLinkInsertion: 45,
      numberOfLinks: "not-tag",
      numberOfLinksMax: "",
      numberOfLinksMin: "",
      numberOfWords: "not-limited",
      numberOfWordsMaxWords: "",
      numberOfWordsMinWords: "",
      otherLinks: "yes",
      taggingArticles: "not-tag",
      websiteUrl: "https://data.fr",
    },
  ];
